Twitter2/Controllers/PublicacionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Database.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repository.Repository;
using Twitter2.ViewModels;

namespace Twitter2.Controllers
{
    [Authorize]
    public class PublicacionController : Controller
    {
        private readonly PublicacionRepository _repository;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly Twitter2Context _context;
        public PublicacionController(PublicacionRepository repository,IWebHostEnvironment hostingEnvironment, Twitter2Context context)
        {
            _repository = repository;
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }
        public async Task<IActionResult> Index(int id)
        { return View(await _repository.Index(id)); }

        [HttpPost]
        public async Task<IActionResult> addComentario(int id, FullPublicacionViewModel viewModel)
        {
            if(viewModel.Comentario != null)
            {
                var usuario = await _context.Usuario.FirstOrDefaultAsync(c => c.UserName == User.Identity.Name);
                if (await _repository.AddComentario(usuario.Foto,User.Identity.Name, id, viewModel))
                {
                    
                 
                    return RedirectToAction("Index", new { id = id });
                }
            }
            return RedirectToAction("Index", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> addReply(int publ,int id, FullPublicacionViewModel viewModel)
        {
            if(viewModel.Reply != null)
            {
                if(await _repository.addReply(User.Identity.Name,id, viewModel))
                {
                    return RedirectToAction("Index", new { id = publ });
                }
                else
                {
                    return RedirectToAction("Index", new { id = publ });
                }
            }
            return RedirectToAction("Index", new { id = publ });
        }
    }
}

Twitter2/Controllers/THomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Repository.Repository;
using Twitter2.ViewModels;

namespace Twitter2.Controllers
{
    [Authorize]
    public class THomeController : Controller
    {
        
        private readonly THomeRepository _repository;

        private readonly IWebHostEnvironment _hostingEnvironment;
        public THomeController(THomeRepository repository,IWebHostEnvironment hostingEnvironment)
        {
            _repository = repository;
            _hostingEnvironment = hostingEnvironment;
        }
        public async Task<IActionResult> Index()
        { return View(await _repository.Home(User.Identity.Name)); }

        [HttpPost]
        public async Task<IActionResult> addPublicacion(THomeViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueName = null;
                if (model.FotoPublicacion != null)
                {
                    var folderPath = Path.Combine(_hostingEnvironment.WebRootPath, "imgs/publ");
                    uniqueName = Guid.NewGuid().ToString() + "_" + model.FotoPublicacion.FileName;
                    var filePath = Path.Combine(folderPath, uniqueName);

                    if (filePath != null)
                    {
                        var stream = new FileStream(filePath, mode: FileMode.Create);
                        model.FotoPublicacion.CopyTo(stream);
                        stream.Flush();
                        stream.Close();
                    }
                }
                if (await _repository.newPubl(uniqueName,User.Identity.Name, model))
                {
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            
            return View(model);
        }

        public async Task<IActionResult> DeletePubl(int id,string name)
        {
           if(await _repository.delPubl(id))
            {
                var folderPath = Path.Combine(_hostingEnvironment.WebRootPath, "imgs/publ");
                var filePathDelete = Path.Combine(folderPath, name);

                 var fileInfo = new FileInfo(filePathDelete);
                    fileInfo.Delete();
                
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditarPubl(int id)
        {
           
          if(await _repository.EditarPubl(id, User.Identity.Name) !=null)
            {
                return View(await _repository.EditarPubl(id, User.Identity.Name));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, PublicacionViewModel viewModel)
        {
          
            if (ModelState.IsValid)
            {
                if(await _repository.Edit(id, viewModel))
                {
                    return RedirectToAction("Index", "THome");
                }

                return RedirectToAction("Index", "THome");

            }
            return RedirectToAction("Index", "THome");

        }

    }
}

Twitter2/Views/THome/EditarPubl.cshtml
@model Twitter2.ViewModels.PublicacionViewModel
@{
    ViewData["Title"] = "EditarPubl";
}

    <div class="container text-left my-3">
        <h3>Editar Publiacion - @Model.UserId </h3>
        <h5 class="text-muted">Fecha de creación - @Model.HoraPublicacion</h5>

        <form asp-action="Editar" asp-route-id="@Model.Id" method="post">
            <div class="form-group">
                <textarea asp-for="Texto" class="form-control" placeholder="Escribe lo que quieras!"></textarea>
            </div>
            <div class="form-group text-right">
                <button class="btn btn-outline-success" type="submit">Publicar!</button>
            </div>
        </form>
    </div>

Twitter2/Views/THome/Index.cshtml
@model Twitter2.ViewModels.THomeViewModel;
@{
    ViewData["Title"] = "Index";
}

    <section class="my-3" style="width:40%; float:left">
        <aside class="card">
            <div class="card-body">

                <div class="my-2">
                    <div class="card-title text-center">
                        @if (Model.FotoUsuario.Length == 0)
                        {
                            <img src="~/imgs/twitter.png" class="img-thumbnail m-1" style="max-width: 19%; float:left" />
                        }
                        else
                        {
                            <img src="~/imgs/users/@Model.FotoUsuario" class="img-thumbnail m-1" style="max-width: 19%; float:left" />
                        }
                        
                        <h3>@Model.Usuario - Bienvenido</h3>
                    </div> <br />
                    <div class="card-body" style="margin-top: 30px">
                        <h4>Amigos:</h4>
                        @foreach (var friends in Model.Amigos)
                        {
                            <div class="card">
                                <div class="card-body custom-control-inline">
                                    <div>
                                        <h5>@friends.Amigo</h5>
                                    </div>
                                    <div class="mx-2">
                                        <a asp-action="EliminarAmigo" asp-route-userid="@friends.Usuario" asp-route-amigo="@friends.Amigo" class="btn btn-outline-danger">Eliminar Amigo</a>
                                    </div>
                                </div>
                            </div>
                            
                        }

                    </div>
                </div>
            </div>
            


        </aside>
    </section>

    <section class="my-0" style="width:58%; float:right">
        

        <div class="container-fluid my-3">
            <form asp-action="addPublicacion" method="post" enctype="multipart/form-data" class="card border-primary">

                <div class="card-body">
                    <div class="form-group">
                        <textarea class="form-control" placeholder="Escribe lo que quieras!" asp-for="TextoPublicacion" required rows="4"></textarea>
                        <span asp-validation-for="TextoPublicacion" class="text-danger"></span>
                    </div>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" asp-for="FotoPublicacion" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04">
                            <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                        </div>
                        
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>

            </form>
            

            @foreach (var publicaciones in Model.Publicaciones)
            {
                <div class="card my-2">
                    <div class="card-body">
                        <h4>@publicaciones.UserId <small class="text-muted">@publicaciones.HoraPublicacion</small></h4>
                        <hr />
                        @if (@publicaciones.Foto ==null)
                        {
                            <img hidden src="~/imgs/publ/@publicaciones.Foto" class="img-thumbnail my-1" />
                        }
                        else
                        {
                            <img src="~/imgs/publ/@publicaciones.Foto" class="img-thumbnail my-1" />

                        }

                        <h5>@publicaciones.Texto</h5>
                    </div>
                    <div class="card-footer">
                        <a asp-action="Index" asp-controller="Publicacion" class="btn btn-outline-info" asp-route-id="@publicaciones.Id">Comentarios</a>|
                        <a asp-action="DeletePubl"  class="btn btn-outline-danger" asp-route-name="@publicaciones.Foto" asp-route-id="@publicaciones.Id">Eliminar</a>|
                        <a asp-action="EditarPubl"  class="btn btn-outline-warning" asp-route-id="@publicaciones.Id">Editar</a>
                    </div>
                </div>
            }

        </div>

    </section>